Add the ASN.1 UTC Time type
huysentruitw/pem-utils pull request #8
Opened 2018-08-13 15:59 UTC by qmfrederik

This adds the `DerAsnUtcTime` class which allows encoding/decoding of UTC Time types.

2018-08-13 17:27 UTC, huysentruitw requested changes

2018-08-13 17:27 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnUtcTime.cs
> +            var timeAsString = $"{time.ToString("yyMMddHHmmss")}Z";
Can you use inline formatting here? Something line `$"{time:yyMMddHHmmss}Z"`?

2018-08-13 17:27 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnUtcTime.cs
> +        public DerAsnUtcTime(DateTime time)
Should take a `DateTimeOffset` + a bool `asUtc` + a bool `includeSeconds`, so it supports all flavors as described in https://www.obj-sys.com/asn1tutorial/node15.html

2018-08-13 17:27 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnUtcTime.cs
> +        public override object Value => _bytes.ToArray();
This should return a parsed DateTimeOffset value, considering all possible flavors. See https://www.obj-sys.com/asn1tutorial/node15.html .

2018-08-13 17:55 UTC, qmfrederik commented
I addressed the straightforward comments; will give the other comments a go later today or tomorrow.

2018-08-13 18:01 UTC, huysentruitw requested changes

2018-08-13 18:01 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnType.cs
> +                case DerAsnTypeTag.UtcTime: return new DerAsnUtcTime(typeData);
While at it, move this line 2 up (between Ia5String and UnicodeString) to keep the same order as in the `DerAsnTypeTag` enum. (makes me sleep better 😄 )

2018-08-14 20:56 UTC, huysentruitw requested changes

2018-08-14 20:56 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnUtcTime.cs
> +            if (time.Offset == TimeSpan.Zero)
First prepare the `timeZonePart` string, after that you only need one `if (includeSeconds)` as you can do `$"{time:yyMMddHHmmss}{timeZonePart}"`

2018-08-14 20:56 UTC, huysentruitw commented on tests/DerConverter.Tests/Asn/DerAsnUtcTime.cs
> +﻿using DerConverter.Asn;
Rename file to DerAsnUtcTimeTests.cs

2018-08-14 21:10 UTC, huysentruitw commented on src/DerConverter/Asn/DerAsnUtcTime.cs
> +        public override object Value => _bytes.ToArray();
Follow up #19

2018-08-14 21:10 UTC, huysentruitw approved these changes

2018-08-14 21:14 UTC, merged